### ISSUE TITLE
Restrictions in the LICENSE

### ISSUE THREAD

**Issue by x2bool** [VitalElement/AvalonStudio#427]
Why the following restrictions are needed?
1. All contributions to the core must be pushed upstream.
2. Forks MUST not re-name the project.
3. Forks MUST retain the AvalonStudio core update repository.
4. Forks using components of the project for other purposes may use the component under MIT.

What is the point of this?

**Comment by danwalmsley** [comment]
It is not allowed for any one to use the code and rebrand it, i.e. For commercial purposes. Idea is you should contribute a plugin, and sell your plug in, not try to sell your own ide.

Its really to avoid the terrible fragmentation and 100s of different versions of eclipse that happened with that project.

It is also to ensure that people contribute to the IDE rather than using it as a starting position to make a competing project.

These restrictions could be lifted or reviewed if you have good reason or suggestions?

**Comment by x2bool** [comment]
I don't see anything wrong with the billion Eclipse forks. The forks are not much worse than the Eclipse itself :)

Even Intellij IDEA uses the standard Apache license. So I don't see the reason to protect the project with additional restrictions.

Besides that the MIT license is well known and predictable. I cannot say the same about this line: "Forks using components of the project for other purposes may use the component under MIT". People can interpret this line in several different ways.

It's not like I am complaining. I was just browsing and found the restrictions. It's a bit unusual.

**Comment by danwalmsley** [comment]
@jameswalmsley do you know why you added MIT caveat?
