### ISSUE TITLE
Perspex nuget package

### ISSUE THREAD

**Issue by susloparovdenis** [VitalElement/AvalonStudio#44]
Cannot build.
AvalonStudio project is depending on Perspex 9999.0.960-nightly nuget package. What a strange version? And what's the purpose of having perspex as git subproject at the same time?

**Comment by danwalmsley** [comment]
Hi, 
 you need to add the Perspex nightly build feed by following the instructions here:

https://github.com/Perspex/Perspex/wiki/Using-nightly-build-feed

The reason we have a sub-project also is because both Perspex and AvalonStudio are in very early stages, and we sometimes contribute new components and fixes to Perspex, having it there makes this convenient, but its not intended to be permanently like that.

I was just curious if you are looking at AvalonStudio with the view of contributing, or to evaluate it as a tool to use?

**Comment by danwalmsley** [comment]
Ah I saw you came from Perspex,, that explains it :D

**Comment by danwalmsley** [comment]
Adding information to Wiki to cover this.
