### ISSUE TITLE
[question] Why not a visual studio code plugin ?

### ISSUE THREAD

**Issue by Driky** [VitalElement/AvalonStudio#690]
Hello contributors,

I just discovered this very interesting project. Impressive work ! But I'm left with a question as stated in the title : 

**Why not write a plugin for visual studio code ?**

It is true that AvalonStudio is an IDE where code is an editor, but with a plugin it can become similar to an IDE. Understand that is not a negative critic against your works but a simple question :)

**Comment by danwalmsley** [comment]
This project wasn't started for Avalonia, it was started to provide a 1st class cross platform ide experience for embedded developers (c/c++)

since its written on Avalonia, it should support Avalonia as a second goal. The aim is to allow any language, toolchain, debugger toolchain through extensibility.

Avalonia team have attempted to make a VSCode previewer and due to the missing of the I in IDE for VSCode its a technical challenge to make it work.

AvalonStudio is nearing a stable release at that point it will be easy to create and develop rich xaml applications for avalonia using mac, linux or pc.
